import type { NextPage } from "next";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <h1>hello</h1>
    </div>
  );
};

export default Home;
